#!/bin/sh

# 서비스 이름
SERVICE="storagepanel"
BIN_PATH="/var/packages/${SERVICE}/target/bin/storagepanel.sh"

case "$1" in
    start)
        echo "Starting $SERVICE..."
        ${BIN_PATH} start
        ;;
    stop)
        echo "Stopping $SERVICE..."
        ${BIN_PATH} stop
        ;;
    status)
        ${BIN_PATH} status
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac

exit 0
