name: Build n Release Synology Custom Packages

on:
    push:
        tags:
            - '*'
    workflow_dispatch:
    
jobs:
    build-spk:
        name: Build Package
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 1
            matrix:
                dsm: ['7.2']
                arch: ['apollolake']
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Synology Package Builder Github Action
              uses: tomgrv/synology-package-builder@v1.3.0
              with:
                  dsm: ${{ matrix.dsm }}
                  arch: ${{ matrix.arch }}
                  projects: Changepanelsize:./ChangePanelSize
                  output: ./dist
            - name: Upload Package
              uses: actions/upload-artifact@v4
              with:
                  name: packages-${{ matrix.dsm }}-${{ matrix.arch }}
                  path: ./dist/*.spk

    create-release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: build-spk
        if: startsWith(github.ref, 'refs/tags/')
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download Package Artifact
              uses: actions/download-artifact@v4
              with:
                  path: ./dist
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./dist/*.zip
                  draft: false
                  prerelease: false
